 #  CATEGORY----------------------------------------------------------------


 # GETTING_ ALL CATEGORY

###
GET http://localhost:8000/

 
 GETTING CATEGORY BY_ID
###
GET http://localhost:8000/category/2

DELETTING CATEGORY
###

DELETE http://localhost:8000/category/10



ISERTING CATEGORY
###

POST http://localhost:8000/category
 Content-Type: application/json

    {
    "id": 4,
    "name": "kimzkim"
  }

###
GET http://localhost:8000/categoryrelation



 
 #  COMMENT----------------------------------------------------------------


 # GETTING_ COMMENT
###
GET http://localhost:8000/comment
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGYWl0aCBLaW1hbmkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTg1MzIzODl9.9pN4xvhNsKBha7h-u2kxbQUWGiEVwj3N1ZcK--S63L0

###

GET http://localhost:8000/comment/13
 


DELETTING COMMENT
###

DELETE http://localhost:8000/comment/3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGYWl0aCBLaW1hbmkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTg1MzIzODl9.9pN4xvhNsKBha7h-u2kxbQUWGiEVwj3N1ZcK--S63L0




ISERTING COMMENT
###

POST http://localhost:8000/comment
Content-Type: application/json

  {
   
    "order_id": 5,
    "user_id": 13,
    "comment_text": "good",
    "is_complaint": "yes",
    "is_praise": "no"
    
  }


 #  STATES----------------------------------------------------------------
###

GET  http://localhost:8000/states

###
GET  http://localhost:8000/states/4
###

DELETE http://localhost:8000/states/3
###

POST  http://localhost:8000/states
Content-Type: application/json

{
   
    "name": "Kigali",
    "code":"124"
}

###

PUT http://localhost:8000/states/4
Content-Type: application/json

{
  "name": "Kigali",
  "code": "1234"
}


#  GETTING ALL USERS----------------------------------------------------------------
###

GET http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGYWl0aCBLaW1hbmkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTg1MzIzODl9.9pN4xvhNsKBha7h-u2kxbQUWGiEVwj3N1ZcK--S63L0

# Getting user by ID
###
GET http://localhost:8000/users/12

###
#Deleting user by ID
DELETE http://localhost:8000/users/152
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGYWl0aCBLaW1hbmkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTg1MzIzODl9.9pN4xvhNsKBha7h-u2kxbQUWGiEVwj3N1ZcK--S63L0

###

POST  http://localhost:8000/users
Content-Type: application/json

{

  "name": "Faith KIMANI wairimu",
  "contact_phone": "+254791339188",
  "phone_verified": true,
  "email": "elijahkimani1293@gmail.com",
  "email_verified": true,
  "confirmation_code": "65566",
  "password": "407363"
 # "created_at": null
#   "updated_at": null
}
###
PUT http://localhost:8000/users/11
Content-Type: application/json

{
  "name":"Faith KIMANI Kim",
  "contact_phone": "+254791339166",
  "phone_verified":false
}

###

 POST   http://localhost:8000/auth/register
Content-Type: application/json

  { 
    "userId":14,
    "username": "Faith Kimani",
    "password": "4028765455",
     "role":"admin"
    
  }

###

POST    http://localhost:8000/auth/login
Content-Type: application/json

  {  
    "username": "Faith Kimani",
    "password": "4028765455"
  }

###
GET http://localhost:8000/users/12




# GETTING_ ALL ADDRESS----------------------------------------------------------------
###
GET http://localhost:8000/address

 
 GETTING ADDRESS BY_ID
###
GET http://localhost:8000/address/5

DELETTING ADDRESS
###

DELETE http://localhost:8000/address/5



ISERTING ADDRESS

###
 POST http://localhost:8000/insert
 Content-Type: application/json

{
    
    "street": "Kigali",
    "postal_code": "123"
 
}

###

PUT http://localhost:8000/update/5
Content-Type: application/json

     {
      "street_address_1": "Kigali",
      "pzip_code_2": "124"
     }

###
GET http://localhost:8000/addressrelation


# RESTAURANT----------------------------------------------------------------------- 

 # GETTING_ ALL CITY
###
GET http://localhost:8000/city

 
 GETTING CITY BY_ID
###
GET http://localhost:8000/city/5

DELETTING CITY
###

DELETE http://localhost:8000/city/50



ISERTING CITY
###

POST http://localhost:8000/insert
 Content-Type: application/json

 {
     "name": "nai",
     "state_id": 3242
 }

###
PUT http://localhost:8000/city/4
Content-Type: application/json

{
  "name": "kimkim",
  "state_id": null
}

###
GET http://localhost:8000/cityrelation


 
# RESTAURANT----------------------------------------------------------------

 # GETTING_ ALL RESTAURANT
###
GET http://localhost:8000/restaurant

 
 GETTING RESTAURANT BY_ID
###
GET http://localhost:8000/restaurant/8

DELETTING RESTAURANT
###

DELETE http://localhost:8000/restaurant/1



ISERTING RESTAURANT
###

POST http://localhost:8000/insert
 Content-Type: application/json
 
 {
  "name": "kimkim",
  "street_address": 34565,
  "zip_code": 5985
#   "city_id": "767"
 }


###
PUT http://localhost:8000/update/8
Content-Type: application/json

{
  "name": "kimkim",
  "street_address": 55556,
  "zip_code": 654
}
 


#  MENU_ITEM----------------------------------------------------------------


 # GETTING_ ALL MENU_ITEM
###
GET http://localhost:8000/restaurant_owner

 
 GETTING RESTAURANT_OWNER BY_ID
###
GET http://localhost:8000/restaurant_owner/5


DELETTING RESTAURANT_OWNER
###

DELETE http://localhost:8000/restaurant_owner/2



ISERTING RESTAURANT_OWNER
###

POST http://localhost:8000/restaurant_owner
 Content-Type: application/json

  {
    "id": 6,
    "restaurant_id":2,
    "owner_id": 2
  }






 #  MENU_ITEM----------------------------------------------------------------


 # GETTING_ ALL ITEM
###
GET http://localhost:8000/menu_item

 
 GETTING MENU_ITEM  BY_ID
###
GET http://localhost:8000/menu_item/5

DELETTING MENU_ITEM
###

DELETE http://localhost:8000/menu_item/1



ISERTING MENU_ITEM
###

POST http://localhost:8000/insert
 Content-Type: application/json







 #  ORDER----------------------------------------------------------------


 # GETTING_ ALL ORDER
###
GET http://localhost:8000/orders

 
 GETTING ORDER BY_ID
###
GET http://localhost:8000/orders/5

DELETTING ORDER
###

DELETE http://localhost:8000/orders/1



ISERTING ORDERS
###

POST http://localhost:8000/insert
 Content-Type: application/json


 #  ORDER_MENU_ITEM----------------------------------------------------------------


 # GETTING_ ALL ORDER_MENU_ITEM
###
GET http://localhost:8000/order_menu_item

 
 GETTING  ORDER_MENU_ITEM BY_ID
###
GET http://localhost:8000/order_menu_item/5

DELETTING ORDER_MENU_ITEM
###

DELETE http://localhost:8000/order_menu_item/5



ISERTING ORDER_MENU_ITEM
###

POST http://localhost:8000/insert
 Content-Type: application/json

{
    "id": 5,
    "order_id":null,
    "menu_item_id": null,
    "quantity": null,
    "item_price":null ,
    "price":null ,
    "comment": null
  }



 #  ORDER_STATUS----------------------------------------------------------------


 # GETTING_ ALL ORDER_STATUS
###
GET http://localhost:8000/order_status

 
 GETTING  ORDER_STATUS  
###
GET http://localhost:8000/order_status/5


DELETTING ORDER_STATUS
###

DELETE http://localhost:8000/order_status/4


ISERTING ORDER_STATUS
###

POST http://localhost:8000/insert
 Content-Type: application/json

 
  {
    "id": 7,
    "order_id": null,
    "status_catalog_id": null,
    "created_at": null
  }


 
 #  ORDER_CATALOG----------------------------------------------------------------


 # GETTING_ ALL STATUS_CATALOG
###
GET http://localhost:8000/status_catalog

 
 GETTING  STATUS_CATALOG
###
GET http://localhost:8000/status_catalog/1

DELETTING STATUS_CATALOG
###

DELETE http://localhost:8000/status_catalog/2



ISERTING STATUS_STATUS
###

POST http://localhost:8000/status_catalog
 Content-Type: application/json

   {
    "id": 7,
    "name": "sumkim"
  }




 
 #  DRIVER----------------------------------------------------------------


 # GETTING_ DRIVER
###
GET http://localhost:8000/driver

 
 GETTING  DRIVER
###
GET http://localhost:8000/driver/2

DELETTING DRIVER
###

DELETE http://localhost:8000/driver/5



ISERTING DRIVER
###

POST http://localhost:8000/insert
 Content-Type: application/json

{
   "id": 7,
  "car_make": "china",
  "car_model": "audi",
  "car_year": 2024,
  "user_id": 12,
  "online": true,
  "delivering": true,
  "created_at": null
}