###

GET  http://localhost:8000/state/states

###
GET  http://localhost:8000/state/state/4
###

DELETE http://localhost:8000/state/delete/3
###

POST  http://localhost:8000/state/insert
Content-Type: application/json

{
   
    "name": "Kigali",
    "code":"124"
}

###

PUT http://localhost:8000/state/update/4
Content-Type: application/json

{
  "name": "Kigali",
  "code": "1234"
}



#  GETTING ALL USERS----------------------------------------------------------------
###

GET http://localhost:8000/users/Users
   Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGYWl0aCBLaW1hbmkiLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODIyOTgyNn0.YeiZwDrq7ZcZFHeIo7-3Nf5N08dF6enSkafE4iCatFs

###

# Getting user by ID
GET http://localhost:8000/users/Users/12

###
#Deleting user by ID
DELETE http://localhost:8000/users/Users/152

###


POST  http://localhost:8000/users/insert
Content-Type: application/json

{

  "name": "Faith KIMANI wairimu",
  "contact_phone": "+254791339188",
  "phone_verified": true,
  "email": "elijahkimani1293@gmail.com",
  "email_verified": true,
  "confirmation_code": "65566",
  "password": "407363"
 # "created_at": null
#   "updated_at": null
}
###
PUT http://localhost:8000/users/update/11
Content-Type: application/json

{
  "name":"Faith KIMANI Kim",
  "contact_phone": "+254791339166",
  "phone_verified":false
}

###

 POST   http://localhost:8000/Auth/register
Content-Type: application/json

  { 
    "userId":13,
    "username": "Faith Kimani",
    "password": "4028765455"
    
  }

###

POST    http://localhost:8000/Auth/login
Content-Type: application/json

  {  
    "username": "Faith Kimani",
    "password": "4028765455"
  }

###
GET http://localhost:8000/Auth/Users/12




# GETTING_ ALL ADDRESS----------------------------------------------------------------
###
GET http://localhost:8000/address/address

 
 GETTING ADDRESS BY_ID
###
GET http://localhost:8000/address/address/5

DELETTING ADDRESS
###

DELETE http://localhost:8000/address/address/5



ISERTING ADDRESS

###
 POST http://localhost:8000/address/insert
 Content-Type: application/json

{
    
    "street": "Kigali",
    "postal_code": "123"
 
}

###

PUT http://localhost:8000/address/update/5
Content-Type: application/json

     {
      "street_address_1": "Kigali",
      "pzip_code_2": "124"
     }



# RESTAURANT----------------------------------------------------------------------- 

 # GETTING_ ALL CITY
###
GET http://localhost:8000/city/city

 
 GETTING CITY BY_ID
###
GET http://localhost:8000/city/city/5

DELETTING CITY
###

DELETE http://localhost:8000/city/city/50



ISERTING CITY
###

POST http://localhost:8000/city/insert
 Content-Type: application/json

 {
     "name": "nai",
     "state_id": 3242
 }

###
PUT http://localhost:8000/city/update/5
Content-Type: application/json

{
  "name": "kimkim",
  "state_id": null
}


 
# RESTAURANT----------------------------------------------------------------

 # GETTING_ ALL RESTAURANT
###
GET http://localhost:8000/restaurant/restaurant

 
 GETTING RESTAURANT BY_ID
###
GET http://localhost:8000/restaurant/restaurant/8

DELETTING RESTAURANT
###

DELETE http://localhost:8000/restaurant/delete/1



ISERTING RESTAURANT
###

POST http://localhost:8000/restaurant/insert
 Content-Type: application/json
 
 {
  "name": "kimkim",
  "street_address": 34565,
  "zip_code": 5985
#   "city_id": "767"
 }


###
PUT http://localhost:8000/restaurant/update/8
Content-Type: application/json

{
  "name": "kimkim",
  "street_address": 55556,
  "zip_code": 654
}
 


#  MENU_ITEM----------------------------------------------------------------


 # GETTING_ ALL MENU_ITEM
###
GET http://localhost:8000/restaurant_owner/restaurant_owner

 
 GETTING RESTAURANT_OWNER BY_ID
###
GET http://localhost:8000/restaurant_owner/restaurant_owner/5


DELETTING RESTAURANT_OWNER
###

DELETE http://localhost:8000/restaurant_owner/delete/2



ISERTING RESTAURANT_OWNER
###

POST http://localhost:8000/restaurant_owner/insert
 Content-Type: application/json


 #  CATEGORY----------------------------------------------------------------


 # GETTING_ ALL CATEGORY
###
GET http://localhost:8000/category/category

 
 GETTING CATEGORY BY_ID
###
GET http://localhost:8000/category/category/2

DELETTING CATEGORY
###

DELETE http://localhost:8000/category/delete/1



ISERTING CATEGORY
###

POST http://localhost:8000/category/insert
 Content-Type: application/json

   {
    "id": 2,
    "name": "kimzkim"
  }



 #  MENU_ITEM----------------------------------------------------------------


 # GETTING_ ALL ITEM
###
GET http://localhost:8000/menu_item/menu_item

 
 GETTING MENU_ITEM  BY_ID
###
GET http://localhost:8000/menu_item/menu_item/5

DELETTING MENU_ITEM
###

DELETE http://localhost:8000/menu_item/delete/1



ISERTING MENU_ITEM
###

POST http://localhost:8000/menu_item/insert
 Content-Type: application/json







 #  ORDER----------------------------------------------------------------


 # GETTING_ ALL ORDER
###
GET http://localhost:8000/orders/orders

 
 GETTING ORDER BY_ID
###
GET http://localhost:8000/orders/orders/5

DELETTING ORDER
###

DELETE http://localhost:8000/orders/delete/1



ISERTING ORDERS
###

POST http://localhost:8000/orders/insert
 Content-Type: application/json


 #  ORDER_MENU_ITEM----------------------------------------------------------------


 # GETTING_ ALL ORDER_MENU_ITEM
###
GET http://localhost:8000/order_menu_item/order_menu_item

 
 GETTING  ORDER_MENU_ITEM BY_ID
###
GET http://localhost:8000/order_menu_item/order_menu_item/5

DELETTING ORDER_MENU_ITEM
###

DELETE http://localhost:8000/order_menu_item/delete/5



ISERTING ORDER_MENU_ITEM
###

POST http://localhost:8000/order_menu_item/insert
 Content-Type: application/json

{
    "id": 5,
    "order_id":null,
    "menu_item_id": null,
    "quantity": null,
    "item_price":null ,
    "price":null ,
    "comment": null
  }



 #  ORDER_STATUS----------------------------------------------------------------


 # GETTING_ ALL ORDER_STATUS
###
GET http://localhost:8000/order_status/order_status

 
 GETTING  ORDER_STATUS  
###
GET http://localhost:8000/order_status/order_status/5


DELETTING ORDER_STATUS
###

DELETE http://localhost:8000/order_status/delete/4


ISERTING ORDER_STATUS
###

POST http://localhost:8000/order_status/insert
 Content-Type: application/json

 
  {
    "id": 7,
    "order_id": null,
    "status_catalog_id": null,
    "created_at": null
  }


 
 #  ORDER_CATALOG----------------------------------------------------------------


 # GETTING_ ALL STATUS_CATALOG
###
GET http://localhost:8000/status_catalog/status_catalog

 
 GETTING  STATUS_CATALOG
###
GET http://localhost:8000/status_catalog/status_catalog/1

DELETTING STATUS_CATALOG
###

DELETE http://localhost:8000/status_catalog/delete/2



ISERTING STATUS_STATUS
###

POST http://localhost:8000/status_catalog/insert
 Content-Type: application/json

   {
    "id": 7,
    "name": "sumkim"
  }


 
 #  COMMENT----------------------------------------------------------------


 # GETTING_ COMMENT
###
GET http://localhost:8000/comment/comment

 
 GETTING  COMMENT
###
GET http://localhost:8000/comment/comment/1

DELETTING COMMENT
###

DELETE http://localhost:8000/comment/delete/3



ISERTING COMMENT
###

POST http://localhost:8000/comment/insert
 Content-Type: application/json



 
 #  DRIVER----------------------------------------------------------------


 # GETTING_ DRIVER
###
GET http://localhost:8000/driver/driver

 
 GETTING  DRIVER
###
GET http://localhost:8000/driver/driver/2

DELETTING DRIVER
###

DELETE http://localhost:8000/driver/delete/5



ISERTING DRIVER
###

POST http://localhost:8000/driver/insert
 Content-Type: application/json

{
   "id": 7,
  "car_make": "china",
  "car_model": "audi",
  "car_year": 2024,
  "user_id": 12,
  "online": true,
  "delivering": true,
  "created_at": null
}